// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSearchandFilterFunctionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSearchandFilterFunction() {
    driver.get("https://www.thegioididong.com/");
    driver.manage().window().setSize(new Dimension(1094, 602));
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.id("skw")).sendKeys("samsung");
    driver.findElement(By.id("skw")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".item:nth-child(2) .item-img")).click();
    js.executeScript("window.scrollTo(0,480)");
    driver.findElement(By.cssSelector(".green > .box-price-percent")).click();
    driver.findElement(By.cssSelector(".gray > .box-price-old")).click();
    driver.findElement(By.linkText("MUA NGAY")).click();
    js.executeScript("window.scrollTo(0,735.2000122070312)");
    driver.findElement(By.linkText("Xem tất cả khuyến mãi")).click();
    driver.findElement(By.cssSelector(".active:nth-child(1) > small > a")).click();
    driver.findElement(By.cssSelector(".container > .container")).click();
    js.executeScript("window.scrollTo(0,1706.4000244140625)");
    js.executeScript("window.scrollTo(0,1572.800048828125)");
    js.executeScript("window.scrollTo(0,415.20001220703125)");
    driver.findElement(By.cssSelector(".main-menu > li:nth-child(2)")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > a > span")).click();
    js.executeScript("window.scrollTo(0,597.5999755859375)");
    driver.findElement(By.cssSelector("#gaming .item:nth-child(9) h3")).click();
    js.executeScript("window.scrollTo(0,0.800000011920929)");
    js.executeScript("window.scrollTo(0,468.79998779296875)");
    js.executeScript("window.scrollTo(0,472.79998779296875)");
    driver.findElement(By.cssSelector(".listproduct .owl-next > span")).click();
    driver.close();
  }
}
